# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/22890/Desktop/CS202 Project/CS202_Project/CS202_Project.srcs/sources_1/ip/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/22890/Desktop/CS202 Project/CS202_Project/CS202_Project.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/22890/Desktop/CS202 Project/CS202_Project/CS202_Project.srcs/sources_1/ip/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/22890/Desktop/CS202 Project/CS202_Project/CS202_Project.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
