#reset,clk
set_property IOSTANDARD LVCMOS33 [get_ports fpga_clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset_h]
set_property PACKAGE_PIN Y18 [get_ports fpga_clk]
set_property PACKAGE_PIN P20 [get_ports reset_h]


#display
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[11]}]




set_property PACKAGE_PIN C19 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN E19 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN D19 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN F18 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN E18 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN B20 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN A20 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN A18 [get_ports {seg_en[7]}]

set_property PACKAGE_PIN E13 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN C15 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN C14 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN E17 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN F16 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN F14 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN F13 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN F15 [get_ports {seg_out[7]}]

set_property PACKAGE_PIN M21 [get_ports hsync]
set_property PACKAGE_PIN L21 [get_ports vsync]

set_property PACKAGE_PIN H20 [get_ports {vga_rgb[0]}]
set_property PACKAGE_PIN G20 [get_ports {vga_rgb[1]}]
set_property PACKAGE_PIN K21 [get_ports {vga_rgb[2]}]
set_property PACKAGE_PIN K22 [get_ports {vga_rgb[3]}]
set_property PACKAGE_PIN H17 [get_ports {vga_rgb[4]}]
set_property PACKAGE_PIN H18 [get_ports {vga_rgb[5]}]
set_property PACKAGE_PIN J22 [get_ports {vga_rgb[6]}]
set_property PACKAGE_PIN H22 [get_ports {vga_rgb[7]}]
set_property PACKAGE_PIN G17 [get_ports {vga_rgb[8]}]
set_property PACKAGE_PIN G18 [get_ports {vga_rgb[9]}]
set_property PACKAGE_PIN J15 [get_ports {vga_rgb[10]}]
set_property PACKAGE_PIN H15 [get_ports {vga_rgb[11]}]


#led
set_property PACKAGE_PIN K17 [get_ports {led_out[23]}]
set_property PACKAGE_PIN L13 [get_ports {led_out[22]}]
set_property PACKAGE_PIN M13 [get_ports {led_out[21]}]
set_property PACKAGE_PIN K14 [get_ports {led_out[20]}]
set_property PACKAGE_PIN K13 [get_ports {led_out[19]}]
set_property PACKAGE_PIN M20 [get_ports {led_out[18]}]
set_property PACKAGE_PIN N20 [get_ports {led_out[17]}]
set_property PACKAGE_PIN N19 [get_ports {led_out[16]}]
set_property PACKAGE_PIN M17 [get_ports {led_out[15]}]
set_property PACKAGE_PIN M16 [get_ports {led_out[14]}]
set_property PACKAGE_PIN M15 [get_ports {led_out[13]}]
set_property PACKAGE_PIN K16 [get_ports {led_out[12]}]
set_property PACKAGE_PIN L16 [get_ports {led_out[11]}]
set_property PACKAGE_PIN L15 [get_ports {led_out[10]}]
set_property PACKAGE_PIN L14 [get_ports {led_out[9]}]
set_property PACKAGE_PIN J17 [get_ports {led_out[8]}]
set_property PACKAGE_PIN F21 [get_ports {led_out[7]}]
set_property PACKAGE_PIN G22 [get_ports {led_out[6]}]
set_property PACKAGE_PIN G21 [get_ports {led_out[5]}]
set_property PACKAGE_PIN D21 [get_ports {led_out[4]}]
set_property PACKAGE_PIN E21 [get_ports {led_out[3]}]
set_property PACKAGE_PIN D22 [get_ports {led_out[2]}]
set_property PACKAGE_PIN E22 [get_ports {led_out[1]}]
set_property PACKAGE_PIN A21 [get_ports {led_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]

#switch
set_property IOSTANDARD LVCMOS33 [get_ports {switch[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property PACKAGE_PIN AA8 [get_ports {switch[18]}]
set_property PACKAGE_PIN V8 [get_ports {switch[17]}]
set_property PACKAGE_PIN V9 [get_ports {switch[16]}]
set_property PACKAGE_PIN Y9 [get_ports {switch[23]}]
set_property PACKAGE_PIN W9 [get_ports {switch[22]}]
set_property PACKAGE_PIN Y7 [get_ports {switch[21]}]
set_property PACKAGE_PIN Y8 [get_ports {switch[20]}]
set_property PACKAGE_PIN AB8 [get_ports {switch[19]}]
set_property PACKAGE_PIN AB6 [get_ports {switch[15]}]
set_property PACKAGE_PIN AB7 [get_ports {switch[14]}]
set_property PACKAGE_PIN V7 [get_ports {switch[13]}]
set_property PACKAGE_PIN AA6 [get_ports {switch[12]}]
set_property PACKAGE_PIN Y6 [get_ports {switch[11]}]
set_property PACKAGE_PIN T6 [get_ports {switch[10]}]
set_property PACKAGE_PIN R6 [get_ports {switch[9]}]
set_property PACKAGE_PIN V5 [get_ports {switch[8]}]
set_property PACKAGE_PIN U6 [get_ports {switch[7]}]
set_property PACKAGE_PIN W5 [get_ports {switch[6]}]
set_property PACKAGE_PIN W6 [get_ports {switch[5]}]
set_property PACKAGE_PIN U5 [get_ports {switch[4]}]
set_property PACKAGE_PIN T5 [get_ports {switch[3]}]
set_property PACKAGE_PIN T4 [get_ports {switch[2]}]
set_property PACKAGE_PIN R4 [get_ports {switch[1]}]
set_property PACKAGE_PIN W4 [get_ports {switch[0]}]

#uart
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y19} [get_ports rx]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V18} [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports start_pg]
set_property PACKAGE_PIN P4 [get_ports start_pg]


#keyboard
# set_property PACKAGE_PIN M2 [get_ports {col[3]}]
# set_property PACKAGE_PIN K6 [get_ports {col[2]}]
# set_property PACKAGE_PIN J6 [get_ports {col[1]}]
# set_property PACKAGE_PIN L5 [get_ports {col[0]}]

# set_property PACKAGE_PIN K4 [get_ports {row[3]}]
# set_property PACKAGE_PIN J4 [get_ports {row[2]}]
# set_property PACKAGE_PIN L3 [get_ports {row[1]}]
# set_property PACKAGE_PIN K3 [get_ports {row[0]}]

set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[27]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[8]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[12]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[22]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[6]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[19]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[18]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[14]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[13]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[10]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[2]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[21]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[20]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[29]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[23]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[16]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[15]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[4]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[11]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[7]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[0]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[5]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[9]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[24]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[28]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[31]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[1]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[3]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[17]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[25]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[26]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_1[30]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[11]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[12]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[18]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[23]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[6]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[30]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[5]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[21]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[17]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[4]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[7]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[19]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[15]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[28]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[31]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[25]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[2]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[3]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[8]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[10]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[13]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[16]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[22]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[24]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[26]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[0]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[1]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[9]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[14]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[20]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[27]}]
set_property MARK_DEBUG true [get_nets {ifetch/prgrom/douta[29]}]

set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[7]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[10]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[4]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[5]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[9]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[6]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[12]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[0]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[3]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[13]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[11]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[2]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[1]}]
set_property MARK_DEBUG false [get_nets {ifetch/prgrom/addra[8]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[23]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[20]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[21]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[28]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[11]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[9]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[30]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[26]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[12]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[15]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[14]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[0]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[2]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[13]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[16]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[17]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[24]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[25]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[27]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[31]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[3]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[1]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[4]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[5]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[7]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[10]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[19]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[22]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[6]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[8]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[18]}]
set_property MARK_DEBUG true [get_nets {uram/ram/douta[29]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[11]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[14]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[13]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[17]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[30]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[6]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[5]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[29]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[18]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[10]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[4]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[3]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[12]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[28]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[25]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[21]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[16]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[15]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[7]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[0]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[8]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[9]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[22]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[1]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[2]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[19]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[23]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[24]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[20]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[27]}]
set_property MARK_DEBUG true [get_nets {decoder/Read_data_2[26]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_main/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ifetch/prgrom/douta[0]} {ifetch/prgrom/douta[1]} {ifetch/prgrom/douta[2]} {ifetch/prgrom/douta[3]} {ifetch/prgrom/douta[4]} {ifetch/prgrom/douta[5]} {ifetch/prgrom/douta[6]} {ifetch/prgrom/douta[7]} {ifetch/prgrom/douta[8]} {ifetch/prgrom/douta[9]} {ifetch/prgrom/douta[10]} {ifetch/prgrom/douta[11]} {ifetch/prgrom/douta[12]} {ifetch/prgrom/douta[13]} {ifetch/prgrom/douta[14]} {ifetch/prgrom/douta[15]} {ifetch/prgrom/douta[16]} {ifetch/prgrom/douta[17]} {ifetch/prgrom/douta[18]} {ifetch/prgrom/douta[19]} {ifetch/prgrom/douta[20]} {ifetch/prgrom/douta[21]} {ifetch/prgrom/douta[22]} {ifetch/prgrom/douta[23]} {ifetch/prgrom/douta[24]} {ifetch/prgrom/douta[25]} {ifetch/prgrom/douta[26]} {ifetch/prgrom/douta[27]} {ifetch/prgrom/douta[28]} {ifetch/prgrom/douta[29]} {ifetch/prgrom/douta[30]} {ifetch/prgrom/douta[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {decoder/Read_data_1[0]} {decoder/Read_data_1[1]} {decoder/Read_data_1[2]} {decoder/Read_data_1[3]} {decoder/Read_data_1[4]} {decoder/Read_data_1[5]} {decoder/Read_data_1[6]} {decoder/Read_data_1[7]} {decoder/Read_data_1[8]} {decoder/Read_data_1[9]} {decoder/Read_data_1[10]} {decoder/Read_data_1[11]} {decoder/Read_data_1[12]} {decoder/Read_data_1[13]} {decoder/Read_data_1[14]} {decoder/Read_data_1[15]} {decoder/Read_data_1[16]} {decoder/Read_data_1[17]} {decoder/Read_data_1[18]} {decoder/Read_data_1[19]} {decoder/Read_data_1[20]} {decoder/Read_data_1[21]} {decoder/Read_data_1[22]} {decoder/Read_data_1[23]} {decoder/Read_data_1[24]} {decoder/Read_data_1[25]} {decoder/Read_data_1[26]} {decoder/Read_data_1[27]} {decoder/Read_data_1[28]} {decoder/Read_data_1[29]} {decoder/Read_data_1[30]} {decoder/Read_data_1[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 31 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {decoder/Read_data_2[0]} {decoder/Read_data_2[1]} {decoder/Read_data_2[2]} {decoder/Read_data_2[3]} {decoder/Read_data_2[4]} {decoder/Read_data_2[5]} {decoder/Read_data_2[6]} {decoder/Read_data_2[7]} {decoder/Read_data_2[8]} {decoder/Read_data_2[9]} {decoder/Read_data_2[10]} {decoder/Read_data_2[11]} {decoder/Read_data_2[12]} {decoder/Read_data_2[13]} {decoder/Read_data_2[14]} {decoder/Read_data_2[15]} {decoder/Read_data_2[16]} {decoder/Read_data_2[17]} {decoder/Read_data_2[18]} {decoder/Read_data_2[19]} {decoder/Read_data_2[20]} {decoder/Read_data_2[21]} {decoder/Read_data_2[22]} {decoder/Read_data_2[23]} {decoder/Read_data_2[24]} {decoder/Read_data_2[25]} {decoder/Read_data_2[26]} {decoder/Read_data_2[27]} {decoder/Read_data_2[28]} {decoder/Read_data_2[29]} {decoder/Read_data_2[30]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {uram/ram/douta[0]} {uram/ram/douta[1]} {uram/ram/douta[2]} {uram/ram/douta[3]} {uram/ram/douta[4]} {uram/ram/douta[5]} {uram/ram/douta[6]} {uram/ram/douta[7]} {uram/ram/douta[8]} {uram/ram/douta[9]} {uram/ram/douta[10]} {uram/ram/douta[11]} {uram/ram/douta[12]} {uram/ram/douta[13]} {uram/ram/douta[14]} {uram/ram/douta[15]} {uram/ram/douta[16]} {uram/ram/douta[17]} {uram/ram/douta[18]} {uram/ram/douta[19]} {uram/ram/douta[20]} {uram/ram/douta[21]} {uram/ram/douta[22]} {uram/ram/douta[23]} {uram/ram/douta[24]} {uram/ram/douta[25]} {uram/ram/douta[26]} {uram/ram/douta[27]} {uram/ram/douta[28]} {uram/ram/douta[29]} {uram/ram/douta[30]} {uram/ram/douta[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_cpu]
