# set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
# set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]

# set_property IOSTANDARD LVCMOS33 [get_ports {mode}]

# set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[11]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[12]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[13]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[14]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[15]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[16]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[17]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[18]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[19]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[20]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data[21]}]

# set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]

# set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[7]}]

# set_property IOSTANDARD LVCMOS33 [get_ports {hsync}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vsync}]

# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[11]}]

# set_property PACKAGE_PIN Y18 [get_ports {clk}]
# set_property PACKAGE_PIN Y9 [get_ports {rst_n}]

# set_property PACKAGE_PIN W9 [get_ports {mode}]

# set_property PACKAGE_PIN W4 [get_ports {data[0]}]
# set_property PACKAGE_PIN R4 [get_ports {data[1]}]
# set_property PACKAGE_PIN T4 [get_ports {data[2]}]
# set_property PACKAGE_PIN T5 [get_ports {data[3]}]
# set_property PACKAGE_PIN U5 [get_ports {data[4]}]
# set_property PACKAGE_PIN W6 [get_ports {data[5]}]
# set_property PACKAGE_PIN W5 [get_ports {data[6]}]
# set_property PACKAGE_PIN U6 [get_ports {data[7]}]
# set_property PACKAGE_PIN V5 [get_ports {data[8]}]
# set_property PACKAGE_PIN R6 [get_ports {data[9]}]
# set_property PACKAGE_PIN T6 [get_ports {data[10]}]
# set_property PACKAGE_PIN Y6 [get_ports {data[11]}]
# set_property PACKAGE_PIN AA6 [get_ports {data[12]}]
# set_property PACKAGE_PIN V7 [get_ports {data[13]}]
# set_property PACKAGE_PIN AB7 [get_ports {data[14]}]
# set_property PACKAGE_PIN AB6 [get_ports {data[15]}]
# set_property PACKAGE_PIN V9 [get_ports {data[16]}]
# set_property PACKAGE_PIN V8 [get_ports {data[17]}]
# set_property PACKAGE_PIN AA8 [get_ports {data[18]}]
# set_property PACKAGE_PIN AB8 [get_ports {data[19]}]
# set_property PACKAGE_PIN Y8 [get_ports {data[20]}]
# set_property PACKAGE_PIN Y7 [get_ports {data[21]}]

# set_property PACKAGE_PIN C19 [get_ports {seg_en[0]}]
# set_property PACKAGE_PIN E19 [get_ports {seg_en[1]}]
# set_property PACKAGE_PIN D19 [get_ports {seg_en[2]}]
# set_property PACKAGE_PIN F18 [get_ports {seg_en[3]}]
# set_property PACKAGE_PIN E18 [get_ports {seg_en[4]}]
# set_property PACKAGE_PIN B20 [get_ports {seg_en[5]}]
# set_property PACKAGE_PIN A20 [get_ports {seg_en[6]}]
# set_property PACKAGE_PIN A18 [get_ports {seg_en[7]}]

# set_property PACKAGE_PIN E13 [get_ports {seg_out0[0]}]
# set_property PACKAGE_PIN C15 [get_ports {seg_out0[1]}]
# set_property PACKAGE_PIN C14 [get_ports {seg_out0[2]}]
# set_property PACKAGE_PIN E17 [get_ports {seg_out0[3]}]
# set_property PACKAGE_PIN F16 [get_ports {seg_out0[4]}]
# set_property PACKAGE_PIN F14 [get_ports {seg_out0[5]}]
# set_property PACKAGE_PIN F13 [get_ports {seg_out0[6]}]
# set_property PACKAGE_PIN F15 [get_ports {seg_out0[7]}]

# set_property PACKAGE_PIN M21 [get_ports {hsync}]
# set_property PACKAGE_PIN L21 [get_ports {vsync}]

# set_property PACKAGE_PIN H20 [get_ports {vga_rgb[0]}]
# set_property PACKAGE_PIN G20 [get_ports {vga_rgb[1]}]
# set_property PACKAGE_PIN K21 [get_ports {vga_rgb[2]}]
# set_property PACKAGE_PIN K22 [get_ports {vga_rgb[3]}]
# set_property PACKAGE_PIN H17 [get_ports {vga_rgb[4]}]
# set_property PACKAGE_PIN H18 [get_ports {vga_rgb[5]}]
# set_property PACKAGE_PIN J22 [get_ports {vga_rgb[6]}]
# set_property PACKAGE_PIN H22 [get_ports {vga_rgb[7]}]
# set_property PACKAGE_PIN G17 [get_ports {vga_rgb[8]}]
# set_property PACKAGE_PIN G18 [get_ports {vga_rgb[9]}]
# set_property PACKAGE_PIN J15 [get_ports {vga_rgb[10]}]
# set_property PACKAGE_PIN H15 [get_ports {vga_rgb[11]}]


