# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/CO/Project/CS202_Project/CS202_Project.srcs/sources_1/ip/clk_vga/clk_vga.xci
# IP: The module: 'clk_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/CO/Project/CS202_Project/CS202_Project.srcs/sources_1/ip/clk_vga/clk_vga_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Projects/CO/Project/CS202_Project/CS202_Project.srcs/sources_1/ip/clk_vga/clk_vga.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Projects/CO/Project/CS202_Project/CS202_Project.srcs/sources_1/ip/clk_vga/clk_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Projects/CO/Project/CS202_Project/CS202_Project.srcs/sources_1/ip/clk_vga/clk_vga.xci
# IP: The module: 'clk_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/CO/Project/CS202_Project/CS202_Project.srcs/sources_1/ip/clk_vga/clk_vga_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Projects/CO/Project/CS202_Project/CS202_Project.srcs/sources_1/ip/clk_vga/clk_vga.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Projects/CO/Project/CS202_Project/CS202_Project.srcs/sources_1/ip/clk_vga/clk_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
